# kubernetes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medsched-app-deployment
  labels:
    app: medsched-app
spec:
  replicas: 2 # Runs 2 copies across your nodes for high availability
  selector:
    matchLabels:
      app: medsched-app
  template:
    metadata:
      labels:
        app: medsched-app
    spec:
      containers:
      - name: medsched-app-container
        # We will update this placeholder image path to your AWS ECR path in the next step!
        image: 276739967270.dkr.ecr.us-east-1.amazonaws.com/medsched-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: DB_HOST
          value: "medsched-db.c6tkesg60dib.us-east-1.rds.amazonaws.com" # 👈 Replace with your actual RDS Endpoint address
        - name: DB_NAME
          value: "medsched"
        - name: DB_USER
          value: "medadmin"
        - name: DB_PASSWORD
          value: "SuperSecurePassword123!"